language: go
cache: 
  - hugo
  - go
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_0.56.3_Linux-64bit.deb
  - sudo dpkg -i hugo_0.56.3_Linux-64bit.deb
go:
  - 1.12.7

script: go version

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: master
