language: go
cache: 
   hugo: true
   go: true

install: 
    - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_extended_0.57.2_Linux-64bit.deb
    - sudo dpkg -i hugo_extended_0.57.2_Linux-64bit.deb
    - git clone https://$GH_TOKEN@github.com/zeroryuki/PT-Source $PTSRC

go: 
  - 1.12.7

before_script: 
    - mkdir public
    - npm install -g postcss-cli

script: hugo -s $PTSRC -c $HOME_SRC -d $HOME_SRC/public/

deploy: 
    provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep_history: false
    target_branch: gh-pages
    local_dir: public
    on: 
      branch: master
