name: Main workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Sourcing
      run: |
        git clone https://${token}@github.com/zeroryuki/PT-Source ${HOME}/PT-Source
        cd ${HOME}/PT-Source
      env:
        token: ${{secrets.GH_TOKEN}}
    - name: build test
      uses: zeroryuki/hugo-docker@v0.57.2
      with:
        args: ls -la ${GITHUB_WORKSPACE}
