name: Main workflow

on:
  push:
    branches:
    - test/new-actions

jobs:
  test-build:
    strategy:
      matrix:
        version: [0.56.3, 0.57.2]
        image: [ext-alpine]

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Clone source
      run: |
        git clone https://${token}@github.com/zeroryuki/PT-Source /home/runner/work/Checklist-src/PT-Source
      env:
        token: ${{ secrets.GH_TOKEN }}
    - name: Hugo build
      uses: zeroryuki/hugo-actions@v1.0.1
      with:
        version: ${{ matrix.version }}
        image: ${{ matrix.image }}
        source: PT-Source
        content: Checklist-src
        env: production
        command: -s /src -c /content --gc --minify
      env: 
        SRC: /src
        CNT: /content