name: Main workflow

on:
  push:
    branches:
    - test/new-actions

jobs:
  test-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Clone source
      run: |
        git clone https://${token}@github.com/zeroryuki/PT-Source /home/runner/work/_temp/_github_home/PT-Source
        cd /home/runner/work/_temp/_github_home/PT-Source
      env:
        token: ${{ secrets.GH_TOKEN }}
    - name: Hugo build
      uses: zeroryuki/hugo-docker@v0.57.2
      with:
        args: /go/bin/hugo -s ${SRC} --config ${SRC}/config.toml -C . -l ${SRC}/layouts
      env: 
        SRC: /github/home/PT-Source
        CNT: /github/workspace