name: Main workflow

on:
  push:
    branches:
    - test/new-actions

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Clone source
      run: |
        git clone https://${token}@github.com/zeroryuki/PT-Source ../PT-Source
      env:
        token: ${{ secrets.GH_TOKEN }}
    - name: Hugo build
      uses: peaceiris/actions-hugo@v0.57.2
      with:
        entrypoint: /bin/bash ls -la ${SRC}
      env: 
        SRC: /home/runner/work/Checklist-src/PT-Source
        CNT: /home/runner/work/Checklist-src/Checklist-src