name: Main workflow

on:
  push:
    branches:
    - test/new-actions

jobs:
  test-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Clone source
      run: |
        git clone https://${token}@github.com/zeroryuki/PT-Source /home/runner/work/_temp/_github_home/PT-Source
      env:
        token: ${{ secrets.GH_TOKEN }}
    - name: Hugo build
      uses: peaceiris@actions-hugov0.57.2
      with:
        args: -s ${SRC} -c {CNT} --gc --minify
      env: 
        SRC: /github/home/PT-Source
        CNT: /github/workspace