name: Main workflow

on:
  push:
    branches:
    - test/new-actions

jobs:
  test-build:
    strategy:
      matrix:
        version: [0.56.3, 0.57.2]
        image: [ext-alpine]

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Clone source
      run: |
        git clone https://${token}@github.com/zeroryuki/PT-Source /home/runner/work/Checklist-src/PT-Source
      env:
        token: ${{ secrets.GH_TOKEN }}
    - name: Hugo build
      uses: zeroryuki/hugo-actions@v1.0.0
        entrypoint: env
      env: 
        RUNNER_WORKSPACE: /src
        CNT: /github/workspace