name: Main workflow

on:
  push:
    branches:
    - test/new-actions

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Clone source
      run: |
        git clone https://${token}@github.com/zeroryuki/PT-Source ../PT-Source
        ls -la ../
      env:
        token: ${{ secrets.GH_TOKEN }}