name: Main workflow

on:
  push:
    branches:
    - test/new-actions

jobs:
  test-build:
    strategy:
      matrix:
        version: [0.56.3, 0.57.2]
        image: [ext-debian]

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Clone source
      run: |
        git clone https://${token}@github.com/zeroryuki/PT-Source /home/runner/work/_temp/_github_home/PT-Source
        cd /home/runner/work/_temp/_github_home/PT-Source
      env:
        token: ${{ secrets.GH_TOKEN }}
    - name: Hugo build
      uses: klakegg/actions-hugo@1.0.0
      with:
        version: ${{ matrix.version }}
        image: ${{ matrix.image }}
        source: /github/home/PT-Source
      env: 
        SRC: /github/home/PT-Source
        CNT: /github/workspace