name: Main workflow

on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Test build
      uses: zeroryuki/hugo-docker@v0.57.2
      with:
        args: ls -la ${RUNNER_WORKSPACE}
